name: Build Website APK
on:
  repository_dispatch:
    types: [build-app]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Assets Directory
        run: mkdir -p assets  # ખાતરી કરશે કે ફોલ્ડર છે જ

      - name: Update Web URL
        run: |
          echo "${{ github.event.client_payload.url }}" > assets/url.txt
          cat assets/url.txt # ચેક કરવા માટે કે URL લખાયું છે કે નહીં

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Generated-App
          path: build/app/outputs/flutter-apk/app-release.apk
