name: Build Website APK
on:
  repository_dispatch:
    types: [build-app]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3 હતું ત્યાં v4 કર્યું

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Update Web URL
        run: |
          mkdir -p assets
          echo "${{ github.event.client_payload.url }}" > assets/url.txt

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4 # અહીં પણ v3 નું v4 કરી દીધું
        with:
          name: Generated-App
          path: build/app/outputs/flutter-apk/app-release.apk
